name: student_app
description: A Flutter app for campus placement management.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  printing: ^5.12.0
  path_provider: ^2.1.4
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.2.1
  flutter_carousel_widget: ^2.2.0
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.3.2
  dio: ^5.7.0
  file_picker: ^10.1.2
  syncfusion_flutter_pdfviewer: ^29.1.40
  crypto: ^3.0.3
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/times.ttf
    - assets/fonts/timesbd.ttf
    - .env